---
# This playbook contains common plays that will be run on all nodes.

##
 # OPENSTACK tools.
 #   
- name: Install openstack (apt)
  apt: pkg={{ item }} state=present update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  
  with_items:
   - kvm 
   - libvirt-bin 
   - virtinst 
   - mysql-server 
   - python-mysqldb 
   - bridge-utils 
   - ntp 
   - tgt 
   - open-iscsi 
   - open-iscsi-utils 
   - lvm2 
   - rabbitmq-server 
   - memcached 
   - python-memcache 
   - keystone 
   - python-keystone 
   - python-keystoneclient 
   - glance 
   - glance-api 
   - python-glanceclient 
   - glance-common 
   - glance-registry 
   - python-glance 
   - nova-conductor 
   - nova-api 
   - nova-cert 
   - nova-common 
   - nova-compute 
   - nova-compute-kvm 
   - nova-doc 
   - nova-network 
   - nova-objectstore 
   - nova-scheduler 
   - novnc 
   - nova-consoleauth 
   - nova-volume 
   - python-nova 
   - python-novaclient 
   - python-novaclient 
   - python-nova-adminclient 
   - apache2 
   - libapache2-mod-wsgi 
   - openstack-dashboard

- name: Configure keystone file
  template: src=keystone.conf-$ansible_distribution-$ansible_architecture.j2 dest=/etc/keystone/keystone.conf
  tags: openstack
  notify: restart openstack
  
- name: Configure api-paste file
  template: src=api-paste.ini-$ansible_distribution-$ansible_architecture.j2 dest=/etc/nova/api-paste.ini
  tags: openstack
  notify: restart openstack
         
- name: Configure glance-api-paste page file
  template: src=glance-api-paste.ini-$ansible_distribution-$ansible_architecture.j2 dest=/etc/glance/glance-api-paste.ini
  tags: openstack
  notify: restart openstack
  
- name: Configure glance-api file
  template: src=glance-api.conf-$ansible_distribution-$ansible_architecture.j2 dest=/etc/glance/glance-api.conf
  tags: openstack
  notify: restart openstack

- name: Configure glance-registry file
  template: src=glance-registry.conf-$ansible_distribution-$ansible_architecture.j2 dest=/etc/glance/glance-registry.conf
  tags: openstack
  notify: restart openstack

- name: Configure glance-scrubber file
  template: src=glance-scrubber.conf-$ansible_distribution-$ansible_architecture.j2 dest=/etc/glance/glance-scrubber.conf
  tags: openstack
  notify: restart openstack

- name: Configure glance-registry-paste file
  template: src=glance-registry-paste.ini-$ansible_distribution-$ansible_architecture.j2 dest=/etc/glance/glance-registry-paste.ini 
  tags: openstack
  notify: restart openstack
  
- name: Configure nova file
  template: src=nova.conf-$ansible_distribution-$ansible_architecture.j2 dest=/etc/nova/nova.conf
  tags: openstack
  notify: restart openstack    
      
#- name: Copy the init script
#  copy: src=nis-$ansible_distribution-$ansible_architecture.sh dest=/etc/init.d/nis mode=0755

#- name: Enable nis to be started at boot
#  service: name=nis enabled=yes state=started 
    
#- name: Start the nis service
#  service: name=nis state=started enabled=true
#  tags: nis

- include: copy-keys.yml
