#ansible-playbook jenkins.yml --extra-vars "host=myhost user=myuser" --ask-sudo-pass

- name: apply common configuration to all jenkins slaves
#  hosts: jenkins-slaves
  hosts: albandri
#  user: root
  connection: local
  vars_files:
  - [ "roles/jenkins-slave/vars/defaults.yml" ]
  - [ "roles/jenkins-slave/vars/$ansible_distribution-$ansible_architecture.yml", "roles/jenkins-slave/vars/$ansible_distribution.yml" ]
    
  roles:
    - jenkins-slave
