#see https://blog.trifork.com/2013/04/02/ansible-example-playbook-to-setup-jenkins-slave/

#as root 
#ansible-playbook jenkins-slave.yml -i hosts -vvvv
#as albandri 
#ansible-playbook jenkins-slave.yml -i hosts -vvvv --ask-sudo-pass --sudo
# --extra-vars "jenkins_username=aandrieu jenkins_password=tbd"

- name: apply hostname configuration
  hosts: test-boxes
  user: root
#  connection: local
  
  roles:
    - hostname
  vars_files:
    - [ "roles/hostname/defaults/main.yml" ]
    
# This playbook can be run using vagrant (on virtual box). 
- name: Install zfs
  hosts: test-boxes
  user: root
#  connection: local
  
  roles:
    - zfs
    
- name: apply common configuration to all jenkins slaves
  hosts: test-boxes
  sudo: yes
  user: vagrant
  connection: local    
#  remote_user: vagrant
  vars_files:
  - [ "roles/jenkins-slave/defaults/main.yml" ]
  - [ "roles/jenkins-slave/vars/{{ ansible_distribution }}-{{ ansible_architecture }}.yml", "roles/jenkins-slave/vars/{{ ansible_distribution }}.yml" ]

#  vars_prompt:
#  - name: jenkins_username
#    prompt: "What is your jenkins user?"
#    private: no
#  - name: jenkins_password
#    prompt: "What is your jenkins password?"
#    private: yes

  roles:
    - jenkins-slave

# This playbook can be run using vagrant (on virtual box). 
- name: Install xvbf
  hosts: test-boxes
  user: root
#  connection: local
  
  roles:
    - xvbf
