---
# This playbook deploys a simple standalone Tomcat 7 server. 

- hosts: tomcat-servers 
  user: root

  roles:
    - tomcat

# This playbook deploys a simple standalone JBoss server. 

- hosts: jboss-servers 
  user: root

  roles:
    - jboss-standalone

# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  user: root

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: webservers
  user: root

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  user: root

  roles:
    - db
