---     
#This script is used to configure your workstation (for developer)

#sudo ansible-playbook -i hosts -c local -v workstation.yml | tee setup.log

- hosts: all
  gather_facts: true
  tasks:
    - name: group hosts by distribution
      group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"

- hosts: RedHat-7*:RedHat-6*:CentOS-6*:Ubuntu-12.04:Ubuntu-14.04
  gather_facts: false
  tasks:
    - name: group hosts for supported distributions
      group_by: key="supported"

- hosts: "!supported"
  gather_facts: false
  tasks:
    - name: fail for unsupported distribution
      fail: msg="{{ ansible_distribution }} {{ ansible_distribution_version }}
                 is not a supported OS for a Tower installation.  Supported
                 OSes include Red Hat Enterprise Linux 6/7, CentOS 6, or
                 Ubuntu 12.04/14.04."

- name: apply hostname configuration
  hosts: all
  user: root
#  connection: local
  
  roles:
    - hostname
  vars_files:
    - [ "roles/hostname/defaults/main.yml" ]
  
- name: Apply common configuration to all nodes
  hosts: Ubuntu-12*:Ubuntu-14*
  gather_facts: false
  user: root
#  connection: local
  
  roles:
    - common
    
- name: Apply dns configuration to all nodes
  hosts: Ubuntu-12*:Ubuntu-14*
  gather_facts: false
  user: root
#  connection: local
  
  roles:
    - dns
        
  vars:
       nameserver: 8.8.8.8  
#paris  
#      nameserver1: 10.21.200.3
#      nameserver2: 10.25.200.3
#gdynia      
#      nameserver1: 10.7.109.27
#      nameserver2: 10.7.111.244

- name: Apply security configuration
  hosts: security
  user: root
#  connection: local
  
  roles:
    - security

# This playbook can be run using vagrant (on virtual box). 
- name: Install java
  hosts: java
  user: root
#  connection: local
  
  roles:
    - java
    
- name: Install virtualbox
  hosts: virtualbox
  user: root
#  connection: local
  
  roles:
    - virtualbox
      
- name: Install vagrant
  hosts: vagrant
  user: root
#  connection: local
  
  roles:
    - vagrant
   
- name: Install Docker
  hosts: docker
  user: root
#  connection: local  
  roles:
    - docker

# This playbook can be run using vagrant (on virtual box). 
- name: Install locale
  hosts: locale
  user: root
#  connection: local
  
  roles:
    - locale
    
# This playbook can be run using vagrant (on virtual box). 
- name: Install zabbix-agent
  hosts: zabbix-agent
  user: root
#  connection: local
  
  roles:
    - zabbix-agent
    
# This playbook can be run using vagrant (on virtual box). 
- name: Install webmin
  hosts: webmin
  user: root
#  connection: local
  
  roles:
    - webmin
        
# This playbook can be run using vagrant (on virtual box). 
- name: Install xvbf
  hosts: xvbf
  user: root
#  connection: local
  
  roles:
    - xvbf

## This playbook can be run using vagrant (on virtual box). 
#- name: Install zfs
#  hosts: zfs
#  user: root
##  connection: local
#  
#  roles:
#    - zfs
    
#Use below only if you want your servers to be part of MGR build farm
#- name: Apply administration configuration to all nodes
#  hosts: Ubuntu-12*:Ubuntu-14*
#  gather_facts: false
#  user: root
##  connection: local
#  
#  roles:
#    - administration

- name: Apply configuration to jenkins master
  hosts: jenkins-master
  user: root
#  connection: local

  roles:
    - role: jenkins-master

  vars:
      jenkins_proxy: apache
      jenkins_proxy_hostname: jenkins.myhost.com
#      jenkins_ssh_key_file: "{{resources_to}}/resources/jenkins/ssh_key"    # (you can manage remote files with Stouts.resources role)
      jenkins_ssh_key_file: "~/.ssh/id_rsa.pub"
      jenkins_http_port: 8380
      jenkins_home: /jenkins
      jenkins_java_args:
        - "-Xmx1024m"   
        - "-XX:MaxPermSize=512m"   
        - "-Djava.awt.headless=true"      
      jenkins_prefix: "/jenkins"
#      jenkins_jobs:
#        - name: test
#          action: delete

- name: Apply common configuration to all jenkins slaves
  hosts: jenkins-slaves
  user: root
#  connection: local

  vars_files:
  - [ "roles/jenkins-slave/defaults/main.yml" ]
  - [ "roles/jenkins-slave/vars/{{ ansible_distribution }}-{{ ansible_architecture }}.yml", "roles/jenkins-slave/vars/{{ ansible_distribution }}.yml" ]

#  vars_prompt:
#  - name: jenkins_username
#    prompt: "What is your jenkins user?"
#    private: no
#  - name: jenkins_password
#    prompt: "What is your jenkins password?"
#    private: yes

  roles:
    - jenkins-slave

# This playbook can be run using vagrant (on virtual box). 
- name: Install maven
  hosts: maven
  user: root
#  connection: local
  
  roles:
    - maven

# This playbook can be run using vagrant (on virtual box). 
- name: Install css
  hosts: css
  user: root
#  connection: local
  
  roles:
    - css
    
# This playbook can be run using vagrant (on virtual box). 
- name: Install chrome
  hosts: chrome
  user: root
#  connection: local
  
  roles:
     - role: chrome
     
  vars:     
       google_talkplugin_enabled: yes                       # Enable module
       google_agent_pkg_state: installed # Package states: present or installed or latest

- name: Install nodejs
  hosts: nodejs
  user: root
#  connection: local
  
  roles:
    - nodejs

- name: Install workstation add-on
  hosts: workstation
  user: root
#  connection: local
  
  roles:
    - workstation

- name: Install dropbox
  hosts: workstation
  user: root  
#  sudo: yes
#  sudo_user: "{{ user }}"
#  connection: local
  
  roles:
    - dropbox
    
#- name: Apply swarm configuration to all jenkins slaves
#  hosts: jenkins-swarm
#  user: root
##  connection: local
#
#  vars_prompt:
#  - name: jenkins_username
#    prompt: "What is your jenkins user?"
#    private: no
#  - name: jenkins_password
#    prompt: "What is your jenkins password?"
#    private: yes
#
#  roles:
#    - jenkins-swarm

# This playbook deploys a simple standalone Tomcat 7 server. 
- name: deploy Tomcat 
  hosts: tomcat-servers 
  user: root
#  connection: local
  
  roles:
    - tomcat

# This playbook deploys a simple standalone JBoss server. 

- name: deploy Jboss 
  hosts: jboss-servers 
  user: root
#  connection: local
  
  roles:
    - jboss-standalone

# This playbook deploys a MySQL databse.  

- name: deploy MySQL and configure the databases
  hosts: dbservers
  user: root
#  connection: local
  
  roles:
    - db
    
# This playbook deploys the whole application stack in this site.  

- name: configure and deploy the webservers and application code
  hosts: webservers
  user: root
#  connection: local
  
  roles:
    - web

- name: configure supervisor
  hosts: supervisors
  user: root
#  connection: local
  roles:
    - role: supervisor
    
  vars:    
      name: webserver
      command: python -m SimpleHTTPServer
      directory: /opt/web
# user is the same as base_admin_username      
      user: ubuntu

#- name: configure supervisor
#  hosts: supervisors
#  user: root
##  connection: local
#  roles:
#    - role: supervisor
#      name: fitness
#      command: /workspace/xebium/run.sh
#      directory: /workspace/xebium
## user is the same as base_admin_username      
#      user: ubuntu

- name: Install sonar
  hosts: sonar
  user: root
#  connection: local
  roles:
    - role: sonar
    
  vars:    
#TODO merge sonar-runner.properties.j2 file from jenkins_slave role  
      sonar_analyzer_runner_install: false 
#Handle by jenkins_slave role, Warning it will override settings.xml.j2 from jenkins_slave role      
      maven_install: false
      sonar_mysql_install: true      
      sonar_jdbc_driver: "mysql"
      sonar_jdbc_port: 3306
      sonar_jdbc_pass: microsoft

- name: Install conky
  hosts: workstation
  user: root
#  connection: local
  roles:
    - role: conky

# This playbook can be run using vagrant (on virtual box). 
- name: Install subversion
  hosts: workstation
  user: root
#  connection: local
  roles:
    - role: subversion     
        
