---

dependencies: []

galaxy_info:
  author: klen
  company: Stouts
  description: Ansible role for manage Jenkins CI (installation, plugins, roles)
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - development
  - system
