// license-header java merge-point
//
// Generated by SessionBeanImpl.vsl in andromda-ejb3-cartridge on 03/25/2012 14:35:50.
//
package org.andromda.timetracker.service;

import org.andromda.timetracker.vo.UserDetailsVO;
import org.andromda.timetracker.vo.UserVO;

/**
 * @see UserServiceBase
 *
 * Remember to manually configure the local business interface this bean implements if originally you only
 * defined the remote business interface.  However, this change is automatically reflected in the ejb-jar.xml.
 *
 * Do not specify the javax.ejb.Stateless annotation
 * Instead, the session bean is defined in the ejb-jar.xml descriptor.
 */
// Uncomment to enable webservices for UserServiceBean
// @javax.jws.WebService(endpointInterface = "org.andromda.timetracker.service.UserServiceWSInterface", serviceName = "UserService")
public class UserServiceBean
    extends UserServiceBase
    implements UserServiceRemote
{

    // --------------- Constructors ---------------

    /**
     * Default constructor extending base class default constructor
     */
    public UserServiceBean()
    {
        super();
    }

    // -------- Business Methods Impl --------------

    /**
     * @see UserServiceBase#getAllUsers()
     */
    protected UserVO[] handleGetAllUsers()
        throws Exception
    {
        //TODO: put your implementation here.
        // Dummy return value, just that the file compiles
        return null;
    }

    /**
     * @see UserServiceBase#getUser(String)
     */
    protected UserVO handleGetUser(String username)
        throws Exception
    {
        //TODO: put your implementation here.
        // Dummy return value, just that the file compiles
        return null;
    }

    /**
     * @see UserServiceBase#registerUser(UserDetailsVO)
     */
    protected UserDetailsVO handleRegisterUser(UserDetailsVO userDetailVO)
        throws Exception
    {
        //TODO: put your implementation here.
        // Dummy return value, just that the file compiles
        return null;
    }

    /**
     * @see UserServiceBase#removeUser(UserVO)
     */
    protected void handleRemoveUser(UserVO userVO)
        throws Exception
    {
        //TODO: put your implementation here.
        throw new UnsupportedOperationException("org.andromda.timetracker.service.UserServiceBean.handleRemoveUser(UserVO userVO) Not implemented!");
    }


    // -------- Lifecycle Callback Implementation --------------

}