// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl) on 01/06/2012 01:17:16+0100
package org.andromda.timetracker.web.timetrackerhome;

/**
 * @see org.andromda.timetracker.web.timetrackerhome.HomeController
 */
public class HomeControllerImpl
    extends HomeController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -4065180364394170141L;

}