---
dependencies: []

galaxy_info:
  author: Alban Andrieu
  description: A role for installing workstation
  company: Nabla
  license: GPLv3
  min_ansible_version: 1.6.3
  platforms:
  - name: Ubuntu
    versions:
    - all
    - lucid
    - maverick
    - natty
    - oneiric
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  categories:
  - development

ansigenome_info:
  galaxy_id: ''

  travis: False

  synopsis: |
    A role to install basic tools on every workstations, like basic editors, diff tools, scm, pidgin, nodejs and basic performance tools....
    This role must be splitted into seperate one that will be customizable

  usage: |
    Describe how to use in more detail...

  #custom: |
  #  Any custom output you want after the usage section..
