package com.nabla.project.application.model.person.entity;


// Generated by MyEclipse Persistence Tools
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Activity generated by MyEclipse Persistence Tools
 */
@SuppressWarnings( "serial" )
@Entity
@Table( name = "ACTIVITY", schema = "" /*, uniqueConstraints =
{
@UniqueConstraint( columnNames =
{
"NAME"}
)
}*/ )
public class Activity
    extends AbstractActivity
    implements java.io.Serializable
{
    // Constructors

    /** default constructor */
    public Activity(  )
    {
    }

    /** minimal constructor */
    public Activity( Long id, String name )
    {
        super( id, name );
    }

    /** full constructor */
    /*
    public Activity(Long id, String name, Set<Person> persons) {
            super(id, name, persons);
    }
    */
    public Activity( Long id, int version, String name )
    {
        super(  );
        setId( id );
        setVersion( version );
        setName( name );
    }

    // toString
    public String toString(  )
    {
        return String.format( "Ac[%d,%d,%s]",
                              getId(  ),
                              getVersion(  ),
                              getName(  ) );
    }
}
