---
dependencies: []

galaxy_info:
  author: Alban Andrieu
  description: vagrant
  license: GPLv3
  min_ansible_version: 1.4
  version: 0.1

  platforms:
    - name: Ubuntu
      versions:
        - precise
  categories:
    - development
    - system

ansigenome_info:
  galaxy_id: ''

  travis: True

  synopsis: |
    Describe your role in a few paragraphs....

  usage: |
    Describe how to use in more detail...

  #custom: |
  #  Any custom output you want after the usage section..
