---
galaxy_info:
  author: "Kevin Lynch"
  description: vagrant
  license: MIT
  min_ansible_version: 1.4
  version: 0.1

  platforms:
    - name: Ubuntu
      versions:
        - precise
  categories:
    - development
    - system

dependencies: []
