#imports
import os
import ProjectMacro
#getting local scons environment
Import('env')
localenv = env.Clone()

#exporting headers
localenv.Install(os.path.join(localenv['KTPPIncludesDir'],''), Glob('include/*.h')+Glob('include/*.ipp'))

#explicit links
localenv["LIBS"] = [
	'boost_thread-mt',
	'boost_date_time-mt',
	'cppunit',
]

localenv.Append(LIBS=['main_library'], LIBPATH=['#main_library'])

#building shared library
localenv.SharedLibrary(os.path.join(localenv['KTPPLibDir'],'test_library'), Glob('*.cpp'))
