---
dependencies: []

galaxy_info:
  author: Alban Andrieu
  description: A role for creating supervisor tasks
  company: Nabla
  license: GPLv3
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - all
    - lucid
    - maverick
    - natty
    - oneiric
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  categories:
  - cloud
  - development
  - packaging
  - system
  - web

ansigenome_info:
  galaxy_id: ''

  travis: True

  synopsis: |
    Describe your role in a few paragraphs....

  usage: |
    Describe how to use in more detail...

  #custom: |
  #  Any custom output you want after the usage section..
