---

- name: postgresql | Create sonar postgresql user
  postgresql_user: 
     name="{{sonar_jdbc_user}}"
     password="{{sonar_jdbc_pass}}"
  sudo_user: postgres
  notify: restart sonar
  tags: postgresql_server

- name: postgresql | Create sonar postgresql database
  postgresql_db: 
     name="{{sonar_jdbc_db}}"
     owner="{{sonar_jdbc_user}}"
     encoding='UTF-8'
     lc_collate='en_US.UTF-8'
     lc_ctype='en_US.UTF-8'
     template='template0'
  sudo_user: postgres
  notify: restart sonar
  tags: postgresql_server    
