---

dependencies: []

galaxy_info:
  author: Alban Andrieu
  description: Security software installation and configuration.
  company: Nabla
  license: GPLv3
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
    - system
    - security

ansigenome_info:
  galaxy_id: ''

  travis: True

  synopsis: |
    Describe your role in a few paragraphs....

  usage: |
    Describe how to use in more detail...

  #custom: |
  #  Any custom output you want after the usage section..
