---
- hosts: all
  sudo: true
  roles:
    - { role: ./,
        docker_files_enable: yes,
        jenkins_nginx_proxy: yes,
        jenkins_proxy_auth: yes,
        jenkins_proxy_hostname: localhost,        
        docker_files_enable: yes
      }

  vars:
      jenkins_proxy_auth_users:
        - { name: travis, password: travis }
