galaxy_info:
  author: Adham Helal
  description: "Deploy Zabbix agents for Ubuntu 12.04"
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - precise
  categories:
  - monitoring
