// license-header java merge-point
//
// Generated by: test/SessionTest.vsl in andromda-ejb3-cartridge.
//
package org.andromda.timetracker.service.test;

import org.apache.log4j.Logger;

/**
 * Service test class TimeTrackingServiceTest for testing with TestNG
 * Check the testng.xml for initialization of the EJB3Container before running any tests.
 */
public class TimeTrackingServiceTest
{
    private static final Logger logger = Logger.getLogger(TimeTrackingServiceTest.class);

    // @Test
    // public void testFindTimecards()
    // {
    // try
    // {
    // EJB3Container.getInitialContext("user", "password").lookup("TimeTrackingServiceBean/remote");
    // }
    // catch (final Exception ex)
    // {
    // TimeTrackingServiceTest.logger.warn("Failed test testFindTimecards()", ex);
    // }
    // }
}
