---
dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.

galaxy_info:
  author: Alban Andrieu
  description: Docker on Ubuntu greater than 12.04
  license: GPLv3
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - raring
        - saucy
        - trusty
  categories:
    - development
    - packaging
    - system

ansigenome_info:
  galaxy_id: ''

  travis: False

  synopsis: |
    Describe your role in a few paragraphs....

  usage: |
    Describe how to use in more detail...

  #custom: |
  #  Any custom output you want after the usage section..
