// license-header java merge-point
//
// Generated by: SessionTest.vsl in andromda-ejb3-cartridge.
//
package org.andromda.test.howto6.a.test;

import org.andromda.test.test.EJB3Container;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.testng.annotations.Test;

/**
 * Service test class RentalServiceTest for testing with TestNG
 * Check the testng.xml for initialisation of the EJB3Container before running any tests.
 */
public class RentalServiceTest
{
    private static final Log logger = LogFactory.getLog(RentalServiceTest.class);

    @Test
    public void testGetAllCars()
    {
        // try
        // {
        // org.andromda.test.howto6.a.RentalServiceRemote rentalService = (org.andromda.test.howto6.a.RentalServiceRemote)EJB3Container.getInitialContext().lookup("RentalServiceBean/remote");
        // test implementation
        // }
        // catch (Exception ex)
        // {
        // logger.warn("Failed test testGetAllCars()", ex);
        // }
    }

    @Test
    public void testGetCustomersByName()
    {
        // try
        // {
        // org.andromda.test.howto6.a.RentalServiceRemote rentalService = (org.andromda.test.howto6.a.RentalServiceRemote)EJB3Container.getInitialContext().lookup("RentalServiceBean/remote");
        // test implementation
        // }
        // catch (Exception ex)
        // {
        // logger.warn("Failed test testGetCustomersByName()", ex);
        // }
    }

}
