---
# This playbook contains common plays that will be run on all nodes.

- name: Update APT caches.
  apt: update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  
  
- name: Update the configuration
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  
  template:
    src: etc_apt_apt.conf.d_10general.j2
    dest: /etc/apt/apt.conf.d/10general
    owner: root
    group: root
    mode: 0644
  
- name: Make sure the required packages are installed
  apt: pkg={{ item }} state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'    
  with_items:
    - python-apt
    - python-pycurl
    - unattended-upgrades

- name: Upgrade system
  apt: upgrade={{ apt_upgrade }}
  when: apt_upgrade == "safe" or apt_upgrade == "full" or apt_upgrade == "dist"  
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
#  ignore_errors: yes
  
- name: Checking if Sources are Available
  action: shell echo a$(cat /etc/apt/sources.list | grep $(echo   'http://url/{{ ansible_distribution }}/stable' | tr "[:upper:]" "[:lower:]"  ))
  register: sources
  ignore_errors: True
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  
  
- debug: msg="sources value is {{ sources.stdout }} "

- name: Adding source.
  action: shell echo "deb http://url/{{ ansible_distribution }}/stable      {{ ansible_lsb.codename }} main" | tr "[:upper:]" "[:lower:]" >> /etc/apt/sources.list
  when: "ansible_distribution == 'Debian' and sources.stdout == 'a'"  
#      when: "ansible_os_family == 'RedHat' and sources.stdout == 'a'"

# ansible
- name: Test ansible is installed
  shell: ansible --version
  register: ansible_is_installed
  ignore_errors: yes

- name: Run install script as sudo
  script: setup-ansible.sh
  sudo: yes
  when: "ansible_is_installed|failed and (ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS')"
  register: ansible_init_used_sudo

- name: Run install script without sudo
  script: setup-ansible.sh
  when: ansible_is_installed|failed and ansible_init_used_sudo|skipped

- name: Test ansible is installed
  shell: ansible --version

- name: Install basic tools (apt)
  apt: pkg={{ item }} state=present update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  
  tags: package  
  with_items:
   - wget
   - curl
   - nmap
   - ssh  
   - iotop
   - htop
   - iftop
   - monit   
   - sysstat
   - upstart
   - gksu
   
- name: Install editor tools (apt)
  apt: pkg={{ item }} state=present update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  
  tags: package  
  with_items:   
   - apt-show-versions
   - vim
   - geany
   - gedit
   
#TO CHECK sudo aptitude install cowsay fortunes fortunes-fr

- name: Install cowsay (apt)
  apt: pkg={{ item }} state=present update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  
  tags: package  
  with_items:   
   - aptitude
   - randomize-lines
   - cowsay 
   - fortunes 
   - fortunes-fr   

- name: main | uninstall whoopsie packages
  apt: >
    pkg={{ item }} 
    state=absent
    purge=yes
    force=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  
  tags: package      
  with_items:
    - whoopsie  
    
- name: Install perl (apt)
  apt: pkg={{ item }} state=present update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  
  tags: package  
  with_items:
   - perl       
   - libnet-ssleay-perl
   - openssl
   - libauthen-pam-perl
   - libpam-runtime
   - libio-pty-perl

- name: Install python (apt)
  apt: pkg={{ item }} state=present update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' 
  tags: package   
  with_items:
   - python
   - python-pip 
   - python-dev 
   - python-keyczar
   - python-setuptools
   - python-software-properties   
   - build-essential

#- name: Installing common packages.
#  apt: state=present pkg={{ item }}
#  with_items:
#  - libcap2-bin
#  - libssl-dev   
      
- name: Configure resolv file
  template: src=resolv.conf-{{ ansible_distribution }}-{{ ansible_architecture }}.j2 dest=/etc/resolv.conf
  tags: configure

#needed for pidgin to work in file /etc/resolv.conf
#domain france.effix.fr

#TODO move 
#search misys.global.ad misys.global.ad. nt.france.effix.fr. france.effix.fr. effix.fr.
#inside
#/etc/resolvconf/resolv.conf.d/base  
      
- name: Checks if resolver is working properly (issues with some VBox/Host OS combinations)
  command: host -t A ansible.cc
  register: ns
  ignore_errors: yes

- name: Pushes new resolver configuration is resolver fails
  lineinfile: regexp="^nameserver " line="nameserver {{ nameserver }}" dest=/etc/resolv.conf
  when: ns|failed

- name: Checks if resolver is working properly with new nameserver
  command: host -t A ansible.cc

#- name: Final greeting
#  pause: prompt="Don't worry about all the red above; if you made it here, your Vagrant VMs are probably fine !
#    Please press [Enter]"
    
    
#below it can be customized
- name: Append additional sources (apt)
  apt_repository: repo={{ item }} update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'    
  with_items: apt_repositories

- name: Install additional packages (apt)
  apt: pkg={{item}}
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'       
  when: apt_install_packages 
  with_items: apt_install_packages_list  
