---
- name: vagrant | Create temporary directory
  shell: mktemp -d
  register: tempdir
  sudo: true
  tags:
    - vagrant

- name: vagrant | Download vagrant
  get_url: url={{ vagrant_url }} dest={{ vagrant_dir_tmp }}/vagrant.deb
  tags:
    - vagrant

- name: vagrant | Install vagrant
  command: dpkg -i {{ vagrant_dir_tmp }}/vagrant.deb
  tags:
    - vagrant

- name: vagrant | Install libvirt requirements (Debian only)
  apt: pkg={{ item }} state=present
  when: ansible_distribution == 'Debian' and vagrant_libvirt_enabled   
  with_items:
    - libxslt-dev 
    - libxml2-dev 
    - libvirt-dev
    
- name: vagrant | Install libvirt requirements (CentOS only)
  yum: pkg={{ item }} state=present
  when: ansible_distribution == 'CentOS' and vagrant_libvirt_enabled   
  with_items:
    - libxslt-devel 
    - libxml2-devel 
    - libvirt-devel   
    
- name: vagrant | Install libvirt plugin
  command: vagrant plugin install vagrant-libvirt
  when: vagrant_libvirt_enabled   

- name: vagrant | Install gyoku
  command: gem install gyoku -v '1.2.2'
  when: vagrant_windows_enabled   
  
- name: vagrant | Install windows plugin
  command: vagrant plugin install vagrant-windows
  when: vagrant_windows_enabled   

- name: vagrant | Cleanup temporary directory
  file: name={{ tempdir.stdout }} state=absent
  tags:
    - vagrant
