// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * Generated by DaoImpl.vsl in andromda-ejb3-cartridge on 03/25/2012 14:35:52.
 * You can (and have to!) safely modify it by hand.
 */
package org.andromda.timetracker.domain;

import org.apache.log4j.Logger;

/**
 * @see org.andromda.timetracker.domain.UserRole
 */
public class UserRoleDaoImpl extends org.andromda.timetracker.domain.UserRoleDaoBase
{

    private static final Logger logger = Logger.getLogger(UserRoleDaoImpl.class);

    /**
     * @see org.andromda.timetracker.domain.UserRoleDao#toUserRoleVO(org.andromda.timetracker.domain.UserRole, org.andromda.timetracker.vo.UserRoleVO)
     */
    @Override
    public void toUserRoleVO(final org.andromda.timetracker.domain.UserRole sourceEntity, final org.andromda.timetracker.vo.UserRoleVO targetVO)
    {
        // TODO verify behavior of toUserRoleVO
        super.toUserRoleVO(sourceEntity, targetVO);
    }

    /**
     * @see org.andromda.timetracker.domain.UserRoleDao#toUserRoleVO(org.andromda.timetracker.domain.UserRole)
     */
    @Override
    public org.andromda.timetracker.vo.UserRoleVO toUserRoleVO(final org.andromda.timetracker.domain.UserRole entity)
    {
        // TODO verify behavior of toUserRoleVO
        return super.toUserRoleVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private org.andromda.timetracker.domain.UserRole loadUserRoleFromUserRoleVO(final org.andromda.timetracker.vo.UserRoleVO userRoleVO)
    {
        org.andromda.timetracker.domain.UserRole userRole = null;
        if ((userRoleVO != null) && (userRoleVO.getId() != null))
        {
            try
            {
                userRole = this.load(userRoleVO.getId());
            }
            catch (final UserRoleDaoException e)
            {
                UserRoleDaoImpl.logger.debug("UserRoleDaoException" + e);
            }
        }
        if (userRole == null)
        {
            userRole = new UserRole();
        }
        return userRole;
    }

    /**
     * @see org.andromda.timetracker.domain.UserRoleDao#userRoleVOToEntity(org.andromda.timetracker.vo.UserRoleVO)
     */
    @Override
    public org.andromda.timetracker.domain.UserRole userRoleVOToEntity(final org.andromda.timetracker.vo.UserRoleVO userRoleVO)
    {
        // TODO verify behavior of userRoleVOToEntity
        final org.andromda.timetracker.domain.UserRole entity = this.loadUserRoleFromUserRoleVO(userRoleVO);
        this.userRoleVOToEntity(userRoleVO, entity, true);
        return entity;
    }

    /**
     * @see org.andromda.timetracker.domain.UserRoleDao#userRoleVOToEntity(org.andromda.timetracker.vo.UserRoleVO, org.andromda.timetracker.domain.UserRole)
     */
    @Override
    public void userRoleVOToEntity(final org.andromda.timetracker.vo.UserRoleVO sourceVO, final org.andromda.timetracker.domain.UserRole targetEntity, final boolean copyIfNull)
    {
        // TODO verify behavior of userRoleVOToEntity
        super.userRoleVOToEntity(sourceVO, targetEntity, copyIfNull);
    }
}
