// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * Generated by DaoImpl.vsl in andromda-ejb3-cartridge on 03/25/2012 14:35:52.
 * You can (and have to!) safely modify it by hand.
 */
package org.andromda.timetracker.domain;

import org.andromda.timetracker.vo.UserRoleVO;

/**
 * @see UserRole
 */
public class UserRoleDaoImpl
    extends UserRoleDaoBase
{
    /**
     * @see org.andromda.timetracker.domain.UserRoleDao#toUserRoleVO(UserRole, UserRoleVO)
     */
    public void toUserRoleVO(
        UserRole sourceEntity,
        UserRoleVO targetVO)
    {
        // TODO verify behavior of toUserRoleVO
        super.toUserRoleVO(sourceEntity, targetVO);
    }


    /**
     * @see org.andromda.timetracker.domain.UserRoleDao#toUserRoleVO(UserRole)
     */
    public UserRoleVO toUserRoleVO(final UserRole entity)
    {
        // TODO verify behavior of toUserRoleVO
        return super.toUserRoleVO(entity);
    }


    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private UserRole loadUserRoleFromUserRoleVO(UserRoleVO userRoleVO)
    {
        // TODO implement loadUserRoleFromUserRoleVO
        throw new UnsupportedOperationException("org.andromda.timetracker.domain.loadUserRoleFromUserRoleVO(UserRoleVO) not yet implemented.");

        /* A typical implementation looks like this:
        UserRole userRole = this.load(userRoleVO.getId());
        if (userRole == null)
        {
            userRole = UserRole.Factory.newInstance();
        }
        return userRole;
        */
    }


    /**
     * @see org.andromda.timetracker.domain.UserRoleDao#userRoleVOToEntity(UserRoleVO)
     */
    public UserRole userRoleVOToEntity(UserRoleVO userRoleVO)
    {
        // TODO verify behavior of userRoleVOToEntity
        UserRole entity = this.loadUserRoleFromUserRoleVO(userRoleVO);
        this.userRoleVOToEntity(userRoleVO, entity, true);
        return entity;
    }


    /**
     * @see org.andromda.timetracker.domain.UserRoleDao#userRoleVOToEntity(UserRoleVO, UserRole)
     */
    public void userRoleVOToEntity(
        UserRoleVO sourceVO,
        UserRole targetEntity,
        boolean copyIfNull)
    {
        // TODO verify behavior of userRoleVOToEntity
        super.userRoleVOToEntity(sourceVO, targetEntity, copyIfNull);
    }

}