- name: install supervisor
  apt: pkg=supervisor state=present update_cache=true
  sudo: yes

- name: configure main supervisor
  template: src=supervisord.conf.j2 dest={{ supervisor_dir }}/supervisord.conf
  tags: supervisor
  sudo: yes    
    
- name: installing task {{ name }}
  template: src=task.conf.j2 dest={{ supervisor_config_dir }}/{{ name }}.conf
  notify:
    - update supervisord
  sudo: yes

- name: restart task {{ name }}
  command: "{{ supervisorctl_command }} restart {{ name }}:*"
  sudo: yes
