---
# This playbook contains common plays that will be run on all nodes.

##
 # CSS compiling tools.
 #
- name: CSS | Install rubygems package
  action: apt pkg=rubygems state=installed
  tags: css

- name: CSS | Install SASS
  action: command gem install sass creates=/usr/local/bin/sass
  tags: css

- name: CSS | Install Susy (no more --pre required as it's 1.0 now)
  action: command gem install susy
  tags: css

- name: CSS | Install Compass
  action: command gem install compass creates=/usr/local/bin/compass
  tags: css

- name: CSS | Install Respond-to
  action: command gem install respond-to
  tags: css
