---

- name: jenkins restart
  service: name=jenkins state=restarted

- name: jenkins create jobs
  shell: java -jar {{jenkins_home}}/jenkins-cli.jar -s http://127.0.0.1:{{jenkins_http_port}}/ {{item.action}}-job {{item.name}}
  with_items: jenkins_jobs

- name: nginx reload
  service: name=nginx state=reloaded

- name: apache restart
  service: name=apache2 state=restarted
