// license-header java merge-point
//
// Generated by: SessionTest.vsl in andromda-ejb3-cartridge.
//
package org.andromda.test.howto10.a.test;

import org.andromda.test.test.EJB3Container;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.testng.annotations.Test;

/**
 * Service test class PaymentServiceTest for testing with TestNG
 * Check the testng.xml for initialisation of the EJB3Container before running any tests.
 */
public class PaymentServiceTest
{
    private static final Log logger = LogFactory.getLog(PaymentServiceTest.class);

    @Test
    public void testRegister()
    {
        // try
        // {
        // org.andromda.test.howto10.a.PaymentServiceRemote paymentService = (org.andromda.test.howto10.a.PaymentServiceRemote)EJB3Container.getInitialContext().lookup("PaymentServiceBean/remote");
        // test implementation
        // }
        // catch (Exception ex)
        // {
        // logger.warn("Failed test testRegister()", ex);
        // }
    }

}
