// license-header java merge-point
//
// Generated by: SessionTest.vsl in andromda-ejb3-cartridge.
//
package org.andromda.test.howto18.a.test;

import org.andromda.test.test.EJB3Container;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.testng.annotations.Test;

/**
 * Service test class UserServiceTest for testing with TestNG
 * Check the testng.xml for initialisation of the EJB3Container before running any tests.
 */
public class UserServiceTest
{
    private static final Log logger = LogFactory.getLog(UserServiceTest.class);

    @Test
    public void testAddUser()
    {
        // try
        // {
        // org.andromda.test.howto18.a.UserServiceRemote userService = (org.andromda.test.howto18.a.UserServiceRemote)EJB3Container.getInitialContext().lookup("UserServiceBean/remote");
        // test implementation
        // }
        // catch (Exception ex)
        // {
        // logger.warn("Failed test testAddUser()", ex);
        // }
    }

    @Test
    public void testGetUser()
    {
        // try
        // {
        // org.andromda.test.howto18.a.UserServiceRemote userService = (org.andromda.test.howto18.a.UserServiceRemote)EJB3Container.getInitialContext().lookup("UserServiceBean/remote");
        // test implementation
        // }
        // catch (Exception ex)
        // {
        // logger.warn("Failed test testGetUser()", ex);
        // }
    }

    @Test
    public void testGetAllUsers()
    {
        // try
        // {
        // org.andromda.test.howto18.a.UserServiceRemote userService = (org.andromda.test.howto18.a.UserServiceRemote)EJB3Container.getInitialContext().lookup("UserServiceBean/remote");
        // test implementation
        // }
        // catch (Exception ex)
        // {
        // logger.warn("Failed test testGetAllUsers()", ex);
        // }
    }

}
