// license-header java merge-point
//
// Generated by: SessionTest.vsl in andromda-ejb3-cartridge.
//
package org.andromda.test.howto18.a.test;

import org.andromda.test.test.EJB3Container;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.testng.annotations.Test;

/**
 * Service test class UserEndPointServiceTest for testing with TestNG
 * Check the testng.xml for initialisation of the EJB3Container before running any tests.
 */
public class UserEndPointServiceTest
{
    private static final Log logger = LogFactory.getLog(UserEndPointServiceTest.class);

    @Test
    public void testAddUser()
    {
        // try
        // {
        // org.andromda.test.howto18.a.UserEndPointServiceRemote userEndPointService = (org.andromda.test.howto18.a.UserEndPointServiceRemote)EJB3Container.getInitialContext().lookup("UserEndPointServiceBean/remote");
        // test implementation
        // }
        // catch (Exception ex)
        // {
        // logger.warn("Failed test testAddUser()", ex);
        // }
    }

    @Test
    public void testGetUser()
    {
        // try
        // {
        // org.andromda.test.howto18.a.UserEndPointServiceRemote userEndPointService = (org.andromda.test.howto18.a.UserEndPointServiceRemote)EJB3Container.getInitialContext().lookup("UserEndPointServiceBean/remote");
        // test implementation
        // }
        // catch (Exception ex)
        // {
        // logger.warn("Failed test testGetUser()", ex);
        // }
    }

}
