// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.gui.metafacades;

import org.andromda.cartridges.gui.GuiGlobals;
import org.andromda.metafacades.uml.TransitionFacade;
import org.andromda.utils.StringUtilsHelper;

/**
 * A Gui trigger is represented by clicking a hyperlink or posting an action form.
 * MetafacadeLogic implementation for org.andromda.cartridges.gui.metafacades.GuiTrigger.
 *
 * @see org.andromda.cartridges.gui.metafacades.GuiTrigger
 */
public class GuiTriggerLogicImpl extends GuiTriggerLogic {
    private static final long serialVersionUID = 34L;

    /**
     * Public constructor for GuiTriggerLogicImpl
     * @see org.andromda.cartridges.gui.metafacades.GuiTrigger
     */
    public GuiTriggerLogicImpl(final Object metaObject, final String context) {
        super(metaObject, context);
    }

    /**
     * @return getTitleKey() + ".notallowed"
     * @see org.andromda.cartridges.gui.metafacades.GuiTrigger#getNotAllowedTitleKey()
     */
    @Override
    protected String handleGetNotAllowedTitleKey() {
        return this.getTitleKey() + ".notallowed";
    }

    /**
     * @return getTriggerKey() + ".title"
     * @see org.andromda.cartridges.gui.metafacades.GuiTrigger#getTitleKey()
     */
    @Override
    protected String handleGetTitleKey() {
        return this.getTriggerKey() + ".title";
    }

    /**
     * @return getTitleKey() + ".reset"
     * @see org.andromda.cartridges.gui.metafacades.GuiTrigger#getResetTitleKey()
     */
    @Override
    protected String handleGetResetTitleKey() {
        return this.getTitleKey() + ".reset";
    }

    /**
     * @see org.andromda.cartridges.gui.metafacades.GuiTriggerLogic#handleGetResetMessageKey()
     */
    @Override
    protected String handleGetResetMessageKey() {
        return this.getResetTitleKey() + ".message";
    }

    /**
     * @return getResetTitleKey() + ".not.allowed"
     * @see org.andromda.cartridges.gui.metafacades.GuiTrigger#getResetNotAllowedTitleKey()
     */
    @Override
    protected String handleGetResetNotAllowedTitleKey() {
        return this.getResetTitleKey() + ".not.allowed";
    }

    /**
     * @return triggerKey
     * @see org.andromda.cartridges.gui.metafacades.GuiTrigger#getTriggerKey()
     */
    @Override
    protected String handleGetTriggerKey() {
        String triggerKey = StringUtilsHelper.toResourceMessageKey(this.getName());

        if (!this.normalizeMessages()) {
            final GuiAction action = this.getGuiAction();
            if (action != null) {
                final GuiView page = (GuiView) action.getInput();
                if (page != null) {
                    triggerKey = page.getMessageKey() + '.' + triggerKey;
                }
            }
        }

        return triggerKey;
    }

    /**
     * @see org.andromda.cartridges.gui.metafacades.GuiTriggerLogic#handleGetTriggerValue()
     */
    @Override
    protected String handleGetTriggerValue() {
        return StringUtilsHelper.toPhrase(this.getName());
    }

    /**
     * @see org.andromda.cartridges.gui.metafacades.GuiTriggerLogic#handleGetTitleValue()
     */
    @Override
    protected String handleGetTitleValue() {
        return this.getTriggerValue();
    }

    /**
     * @see org.andromda.cartridges.gui.metafacades.GuiTriggerLogic#handleGetResetTitleValue()
     */
    @Override
    protected String handleGetResetTitleValue() {
        return "Reset";
    }

    /**
     * @see org.andromda.cartridges.gui.metafacades.GuiTriggerLogic#handleGetResetMessageValue()
     */
    @Override
    protected String handleGetResetMessageValue() {
        return "Reset";
    }

    /**
     * @see org.andromda.cartridges.gui.metafacades.GuiTriggerLogic#handleGetResetNotAllowedTitleValue()
     */
    @Override
    protected String handleGetResetNotAllowedTitleValue() {
        return "You are not allowed to reset";
    }

    /**
     * @see org.andromda.cartridges.gui.metafacades.GuiTriggerLogic#handleGetNotAllowedTitleValue()
     */
    @Override
    protected String handleGetNotAllowedTitleValue() {
        return "You are not allowed to call this action";
    }

    /**
     * @see org.andromda.cartridges.gui.metafacades.GuiTriggerLogic#handleIsActionTrigger()
     */
    @Override
    protected boolean handleIsActionTrigger() {
        return this.getGuiAction() != null;
    }

    /**
     * @see org.andromda.cartridges.gui.metafacades.GuiTriggerLogic#handleGetGuiAction()
     */
    @Override
    protected Object handleGetGuiAction() {
        GuiAction triggerAction = null;

        final TransitionFacade transition = this.getTransition();
        if (transition instanceof GuiAction) {
            triggerAction = (GuiAction) transition;
        }
        return triggerAction;
    }

    private boolean normalizeMessages() {
        final String normalizeMessages = (String) this.getConfiguredProperty(GuiGlobals.NORMALIZE_MESSAGES);
        return Boolean.valueOf(normalizeMessages).booleanValue();
    }
}
