---
# Main list of tasks to be executed.
#
#   Fail the play if it runs on an unsupported platform.
- name: Assert platform is supported
  tags: maven
  assert:
    that:
      - ansible_os_family in ['Archlinux', 'Debian', 'RedHat', 'Suse']


- name: Install Maven download directory (local)
  tags: maven
  local_action: file
    state=directory
    owner=0
    group=0
    mode=2777
    dest={{ ansible_data_path }}


- name: Download Maven (local)
  tags: maven
  sudo: no
  local_action: get_url
    dest={{ ansible_data_path }}/{{ maven_redis_filename }}
    url={{ maven_mirror }}/{{ maven_redis_filename }}
    mode=0644
    sha256sum={{ maven_redis_sha256sum }}


- name: Install Maven installation directory
  tags: maven
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ maven_install_dir }}

# Install the Maven redistributable package to the node
#unarchive below does not work for tar.gz
- name: Install Maven Debian package 
  action: command creates={{ maven_install_dir }}/apache-maven-{{ maven_version }} chdir={{ maven_install_dir }} tar zxvf {{ ansible_data_path }}/{{ maven_redis_filename }} --owner=root
  register: maven_installed
#  ignore_errors: True 
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
 
- name: Install Maven RPM package
  action: command creates={{ maven_install_dir }}/apache-maven-{{ maven_version }} chdir={{ maven_install_dir }} rpm --force -Uvh {{ ansible_data_path }}/{{ maven_redis_filename }}
  register: maven_installed
#  ignore_errors: True
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- debug: msg="maven_installed value is {{ maven_installed }} {{ maven_installed.skipped }} {{ maven_installed.changed }}"

- name: Install Maven
  tags: maven
  unarchive:
    src={{ ansible_data_path }}/{{ maven_redis_filename }}
    dest={{ maven_install_dir }}
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu' and ansible_distribution != 'CentOS' and ansible_distribution != 'Red Hat Enterprise Linux'

- name: Remove Maven archive
  file: path={{ ansible_data_path }}/{{ maven_redis_filename }} state=absent
  when: maven_download_when
  
- name: Install Maven bin directory
  tags: maven
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ maven_bin_path }}


- name: Install Maven binary
  tags: maven
  file:
    state=link
    force=true
    src={{ maven_install_dir }}/apache-maven-{{ maven_version }}/bin/mvn
    dest={{ maven_bin_path }}/mvn
