// license-header java merge-point
//
// Generated by: MetafacadeLogicImpl.vsl in andromda-meta-cartridge.
package org.andromda.cartridges.gui.metafacades;

/**
 * A plain action state represents an operation on the server called by an action. Optionally an
 * action state may defer operations to the controller.
 * MetafacadeLogic implementation for org.andromda.cartridges.gui.metafacades.GuiActionState.
 *
 * @see org.andromda.cartridges.gui.metafacades.GuiActionState
 */
public class GuiActionStateLogicImpl
    extends GuiActionStateLogic
{
    private static final long serialVersionUID = 34L;
    /**
     * Public constructor for GuiActionStateLogicImpl
     * @see org.andromda.cartridges.gui.metafacades.GuiActionState
     */
    public GuiActionStateLogicImpl (Object metaObject, String context)
    {
        super(metaObject, context);
    }
}