FIND_PATH(KPLUS_INCLUDE_DIRS KPLUS.h /usr/include/KPLUS /usr/local/include/KPLUS /kplustp/thirdparty/kondor/kplus_30.3.05000/include)

FIND_LIBRARY(KPLUS_LIBRARY NAMES KPLUS PATH /usr/lib /usr/local/lib /kplustp/thirdparty/kondor/kplus_30.3.05000/lib/sun4sol/opt/shared) 

IF (KPLUS_INCLUDE_DIRS AND KPLUS_LIBRARY)
   SET(KPLUS_FOUND TRUE)
ENDIF (KPLUS_INCLUDE_DIRS AND KPLUS_LIBRARY)


IF (KPLUS_FOUND)
   IF (NOT KPLUS_FIND_QUIETLY)
      MESSAGE(STATUS "Found KPLUS: ${KPLUS_LIBRARY}")
   ENDIF (NOT KPLUS_FIND_QUIETLY)
ELSE (KPLUS_FOUND)
   IF (KPLUS_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find KPLUS")
   ENDIF (KPLUS_FIND_REQUIRED)
ENDIF (KPLUS_FOUND)
