---
# setup the default Java implementation via system environment
#- assert: java_default_implementation in ['oracle', 'openjdk']
#  tags: java

- name: Fail on invalid user data
  tags:
    - java
    - download
  when: java_default_implementation not in ['oracle', 'openjdk']
  fail:
    msg="java_default_implementation must be one of 'oracle' or 'openjdk'"


- name: Install Java default implementation
  tags: java
  template:
    src=java.sh.j2
    dest={{ java_install_dir }}/java.sh
    owner=0
    group=0
    mode=0755


- name: Activate Java system environment configuration
  tags: java
  file:
    state=link
    src={{ java_install_dir }}/java.sh
    dest=/etc/profile.d/java.sh
