# {{ ansible_managed }}
FROM        stackbrew/ubuntu:14.04
#FROM        debian:jessie

VOLUME      ["/var/log/jenkins"]

MAINTAINER  Alban Andrieu "https://github.com/AlbanAndrieu/nabla"

ENV			DEBIAN_FRONTEND noninteractive
#ENV         JENKINS_HOME {{ jenkins_home }}

RUN apt-get update && apt-get clean
RUN apt-get install -q -y openjdk-7-jre-headless 
RUN apt-get install -y tomcat6
RUN apt-get clean

EXPOSE 8080
ENTRYPOINT  ["/etc/init.d/jenkins", "start"]
#ENTRYPOINT ["java", "-jar", "/opt/jenkins.war"]
CMD ["-g", "deamon off;"
