// license-header java merge-point
//
// Generated by test/SessionTest.vsl in andromda-ejb3-cartridge on 03/24/2012 03:09:12.
//
package org.andromda.timetracker.service.test;

import org.apache.log4j.Logger;
import org.testng.annotations.Test;

/**
 * Service test class SecurityServiceTest for testing with TestNG
 * Check the testng.xml for initialisation of the EJB3Container before running any tests.
 */
public class SecurityServiceTest
{
    private static final Logger logger = Logger.getLogger(SecurityServiceTest.class);

    @Test
    public void testGetUserDetails()
    {
        // try
        // {
        // org.andromda.timetracker.service.SecurityServiceRemote securityService =
        // (org.andromda.timetracker.service.SecurityServiceRemote)EJB3Container.getInitialContext("user","password").lookup("SecurityServiceBean/remote");
        // test implementation
        // }
        // catch (Exception ex)
        // {
        // logger.warn("Failed test testGetUserDetails()", ex);
        // }
    }

}
